name: 'Bump MAUI App version'
description: 'Bump ApplicationVersion and ApplicationDisplayVersion'
inputs:
  csproj:
    description: 'Path to csproj file'
    required: true
    default: '1'
  version:
    description: 'Value for ApplicationVersion property'
    required: true
    default: '1'
  displayVersion:
    description: 'Value for ApplicationVersion property'
    required: true
    default: '1.0'
runs:
  using: "composite"
  steps:
    - name: Bump ApplicationVersion (build version)
      run: |
        echo 'Setting ApplicationVersion (build version) to ${{ inputs.version }}'
        sed -rn 's|(<ApplicationVersion>)(.*)(</ApplicationVersion>)|Old: \1\2\3|p' ${{ inputs.csproj }}
        sed -rE -i 'notneeded.bak' 's|(<ApplicationVersion>)(.*)(</ApplicationVersion>)|<ApplicationVersion>${{ inputs.version }}</ApplicationVersion>|g' ${{ inputs.csproj }}
        sed -rn 's|(<ApplicationVersion>)(.*)(</ApplicationVersion>)|New: \1\2\3|p' ${{ inputs.csproj }}   
        
    - name: Bump ApplicationDisplayVersion (build version)
      run: |
        echo 'Setting ApplicationDisplayVersion (build version) to ${{ inputs.displayVersion }}'
        sed -rn 's|(<ApplicationDisplayVersion>)(.*)(</ApplicationDisplayVersion>)|Old: \1\2\3|p' ${{ inputs.csproj }}
        sed -rE -i 'notneeded.bak' 's|(<ApplicationDisplayVersion>)(.*)(</ApplicationDisplayVersion>)|<ApplicationDisplayVersion>${{ inputs.displayVersion }}</ApplicationDisplayVersion>|g' ${{ inputs.csproj }}
        sed -rn 's|(<ApplicationDisplayVersion>)(.*)(</ApplicationDisplayVersion>)|New: \1\2\3|p' ${{ inputs.csproj }}   

